version: '3'

services:

  products:
    container_name: products-ms
    image: paulogabrieljb/ms-products:0.1
    ports:
    - "8000:8000"
    networks:
    - microservices
  
  catalog:
    container_name: catalog-ms
    image: paulogabrieljb/ms-catalog:0.1
    environment:
      PRODUCT_URL: 'products-ms:8000'
    ports:
    - "3000:3000"
    networks:
    - microservices

  order:
    container_name: order-ms
    image: paulogabrieljb/ms-order:0.1
    environment:
     RABBITMQ_HOST: rabbitmq
     RABBITMQ_PORT: 5672
     RABBITMQ_USERNAME: guest
     RABBITMQ_PASSWORD: guest
     RABBITMQ_CHECKOUT_EX: checkout_ex
     RABBITMQ_CHECKOUT_PREFIX: checkout.#
     RABBITMQ_CHECKOUT_QUEUE: checkout_queue
     REDIS_HOST: redis
     REDIS_PORT: 6379
    networks:
    - microservices
    depends_on:
    - redis
    - rabbitmq
    links:
    - redis
    - rabbitmq

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
    - "6379:6379"
    networks:
    - microservices

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
    - "5672:5672"
    - "15672:15672"
    networks: 
    - microservices
    volumes: 
    - rabbitmq_vol:/var/lib/rabbitmq

networks:
  microservices:

volumes:
  rabbitmq_vol: