apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product

  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: paulogabrieljb/ms-products:0.1
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
  selector:
    app: product